use NCOI_Test_Main
go


select distinct p.ProjectId from Project p
inner join Invoice inv on  p.ProjectId = inv.ProjectId
where  p.Deletion_Date is null and ProjectStatusId = 3 and ContactDirectionId = 1 and inv.InvoiceStatusId = 1


SELECT DISTINCT [NCOI_Test_Main].[dbo].[Project].[ProjectId], [NCOI_Test_Main].[dbo].[Project].[OlympusID] AS [OlympusId], [NCOI_Test_Main].[dbo].[Project].[Creation_Date] AS [CreationDate], [NCOI_Test_Main].[dbo].[Project].[Modification_Date] AS [ModificationDate], [NCOI_Test_Main].[dbo].[Project].[Deletion_Date] AS [DeletionDate], [NCOI_Test_Main].[dbo].[Project].[RowVersion], [NCOI_Test_Main].[dbo].[Project].[CreatedBy], [NCOI_Test_Main].[dbo].[Project].[ModifiedBy], 
[NCOI_Test_Main].[dbo].[Project].[DeletedBy], [NCOI_Test_Main].[dbo].[Project].[CompanyID] AS [CompanyId], [NCOI_Test_Main].[dbo].[Project].[Name], [NCOI_Test_Main].[dbo].[Project].[ProjectStatusID] AS [ProjectStatusId], [NCOI_Test_Main].[dbo].[Project].[SaleTypeId], 
[NCOI_Test_Main].[dbo].[Project].[ProjectManagerId], [NCOI_Test_Main].[dbo].[Project].[ProjectCoordinatorId], [NCOI_Test_Main].[dbo].[Project].[AccountManagerId], [NCOI_Test_Main].[dbo].[Project].[ProjectContactId], [NCOI_Test_Main].[dbo].[Project].[LeadTeacherId], 
[NCOI_Test_Main].[dbo].[Project].[StartDate], [NCOI_Test_Main].[dbo].[Project].[EndDate], [NCOI_Test_Main].[dbo].[Project].[LocationId], [NCOI_Test_Main].[dbo].[Project].[EstimatedProjectHours], [NCOI_Test_Main].[dbo].[Project].[IsNCOILocation] AS [IsNcoilocation], [NCOI_Test_Main].[dbo].[Project].[BusinessUnitID] AS [BusinessUnitId], [NCOI_Test_Main].[dbo].[Project].[LocationChosenByID] AS [LocationChosenById], [NCOI_Test_Main].[dbo].[Project].[Memo], [NCOI_Test_Main].[dbo].[Project].[EvcInvoicingTypeID] AS [EvcInvoicingTypeId], [NCOI_Test_Main].[dbo].[Project].[DiscrepancyAmount], [NCOI_Test_Main].[dbo].[Project].[DateWon], [NCOI_Test_Main].[dbo].[Project].[InvoiceMoment], [NCOI_Test_Main].[dbo].[Project].[NumberOfGroups], [NCOI_Test_Main].[dbo].[Project].[NumberOfTeacher], [NCOI_Test_Main].[dbo].[Project].[NumberOfStudents], [NCOI_Test_Main].[dbo].[Project].[ContactDirectionId], [NCOI_Test_Main].[dbo].[Project].[InCompanyProjectStatusId], [NCOI_Test_Main].[dbo].[Project].[CancelDate], [NCOI_Test_Main].[dbo].[Project].[InvoiceMomentTypeId], [NCOI_Test_Main].[dbo].[Project].[CreatedFromNewInCompany], [NCOI_Test_Main].[dbo].[Project].[ProjectTypeId], [NCOI_Test_Main].[dbo].[Project].[LeadTypeId], [NCOI_Test_Main].[dbo].[Project].[LeadEstimation], [NCOI_Test_Main].[dbo].[Project].[StatusChangeReason], [NCOI_Test_Main].[dbo].[Project].[ChanceToGetTheJob] FROM ( [NCOI_Test_Main].[dbo].[Project] 
INNER JOIN [NCOI_Test_Main].[dbo].[Invoice]  ON  [NCOI_Test_Main].[dbo].[Project].[ProjectId]=[NCOI_Test_Main].[dbo].[Invoice].[ProjectId])
WHERE [NCOI_Test_Main].[dbo].[Project].[Deletion_Date] IS NULL AND [NCOI_Test_Main].[dbo].[Project].[ProjectStatusID] = 3 AND [NCOI_Test_Main].[dbo].[Project].[ContactDirectionId] = 1 AND [NCOI_Test_Main].[dbo].[Invoice].[InvoiceStatusID] = 1
